name: IRE
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _pytorch_select=0.2=gpu_0
  - absl-py=0.10.0=py37hc8dfbb8_1
  - astor=0.8.1=pyh9f0ad1d_0
  - blas=1.0=mkl
  - brotlipy=0.7.0=py37hb5d75c8_1001
  - c-ares=1.16.1=h516909a_3
  - ca-certificates=2020.10.14=0
  - certifi=2020.6.20=py37he5f6b98_2
  - cffi=1.14.3=py37he30daa8_0
  - chardet=3.0.4=py37he5f6b98_1008
  - click=7.1.2=pyh9f0ad1d_0
  - cryptography=3.1.1=py37hff6837a_1
  - cudatoolkit=10.2.89=hfd86e86_1
  - cycler=0.10.0=py_2
  - dbus=1.13.6=he372182_0
  - expat=2.2.9=he1b5a44_2
  - filelock=3.0.12=pyh9f0ad1d_0
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.4=h5ab3b9f_0
  - gast=0.4.0=pyh9f0ad1d_0
  - glib=2.66.1=h92f7085_0
  - google-pasta=0.2.0=pyh8c360ce_0
  - gperftools=2.7=h767d802_2
  - grpcio=1.31.0=py37hb0870dc_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - h5py=2.10.0=nompi_py37hf7afa78_105
  - hdf5=1.10.6=nompi_h54c07f9_1110
  - icu=58.2=hf484d3e_1000
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=2.0.0=py_1
  - intel-openmp=2020.2=254
  - jpeg=9b=h024ee3a_2
  - keras-applications=1.0.8=py_1
  - keras-preprocessing=1.1.0=py_0
  - kiwisolver=1.2.0=py37h99015e2_1
  - krb5=1.17.1=hfafb76e_3
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcurl=7.71.1=hcdd3856_8
  - libedit=3.1.20191231=h14c3975_1
  - libev=4.33=h516909a_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.5.0=hae1eefd_17
  - libgfortran4=7.5.0=hae1eefd_17
  - libnghttp2=1.41.0=h8cfc5f6_2
  - libpng=1.6.37=hed695b0_2
  - libprotobuf=3.13.0.1=h8b12597_0
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=hb55368b_3
  - lz4-c=1.9.2=heb0550a_3
  - markdown=3.3.2=pyh9f0ad1d_0
  - matplotlib=3.3.2=py37hc8dfbb8_1
  - matplotlib-base=3.3.2=py37hc9afd2a_1
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37h8f50634_2
  - mkl_fft=1.2.0=py37h161383b_1
  - mkl_random=1.2.0=py37h9fdb41a_1
  - ncurses=6.2=he6710b0_1
  - ninja=1.10.1=hfc4b9b4_2
  - numpy-base=1.19.1=py37hfa32c7d_0
  - olefile=0.46=py37_0
  - openssl=1.1.1h=h516909a_0
  - packaging=20.4=pyh9f0ad1d_0
  - pcre=8.44=he1b5a44_0
  - perl=5.30.3=h516909a_1
  - pillow=8.0.0=py37h9a89aac_0
  - pip=20.2.2=py37_0
  - protobuf=3.13.0.1=py37h3340039_1
  - pthread-stubs=0.4=h14c3975_1001
  - pycparser=2.20=pyh9f0ad1d_2
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyqt=5.9.2=py37hcca6a23_4
  - pysocks=1.7.1=py37he5f6b98_2
  - python=3.7.7=hcff3b4d_5
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.6.0=py3.7_cuda10.2.89_cudnn7.6.5_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=pyh9f0ad1d_0
  - sacremoses=0.0.43=pyh9f0ad1d_0
  - sentencepiece=0.1.92=py37h99015e2_0
  - setuptools=49.6.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.33.0=h62c20be_0
  - tensorboard=1.14.0=py37_0
  - tensorflow=1.14.0=h4531e10_0
  - tensorflow-base=1.14.0=py37h4531e10_0
  - tensorflow-estimator=1.14.0=py37h5ca1d4c_0
  - termcolor=1.1.0=py_2
  - tk=8.6.10=hbc83047_0
  - tokenizers=0.8.1=py37h4c3b196_0
  - torchvision=0.7.0=py37_cu102
  - tornado=6.0.4=py37h8f50634_2
  - transformers=3.3.1=py_0
  - werkzeug=1.0.1=pyh9f0ad1d_0
  - wheel=0.34.2=py37_0
  - wrapt=1.12.1=py37h8f50634_1
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.5=h7b6447c_0
  - zipp=3.3.1=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - fasttext==0.9.2
    - gensim==3.8.3
    - indic-nlp-library==0.71
    - joblib==0.16.0
    - morfessor==2.0.6
    - nltk==3.5
    - numpy==1.19.2
    - pandas==1.1.3
    - pybind11==2.5.0
    - pystemmer==2.0.1
    - pytz==2020.1
    - regex==2020.7.14
    - scipy==1.5.3
    - smart-open==3.0.0
    - tqdm==4.48.2
    - urllib3==1.25.10
