name: IRE
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2020.11.8=ha878542_0
  - certifi=2020.11.8=py37h89c1867_0
  - cycler=0.10.0=py_2
  - freetype=2.10.4=h7ca028e_0
  - jpeg=9d=h36c2ea0_0
  - kiwisolver=1.3.1=py37hc928c03_0
  - lcms2=2.11=hcbb858e_1
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.9.0=2_openblas
  - libcblas=3.9.0=2_openblas
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.5.0=hae1eefd_17
  - libgfortran4=7.5.0=hae1eefd_17
  - liblapack=3.9.0=2_openblas
  - libopenblas=0.3.12=pthreads_hb3c22a3_1
  - libpng=1.6.37=h21135ba_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h4f3a223_6
  - libwebp-base=1.1.0=h36c2ea0_3
  - lz4-c=1.9.2=he1b5a44_3
  - matplotlib-base=3.3.3=py37h4f6019d_0
  - ncurses=6.2=he6710b0_1
  - numpy=1.19.4=py37h7e9df27_1
  - olefile=0.46=pyh9f0ad1d_1
  - openssl=1.1.1h=h516909a_0
  - pillow=8.0.1=py37h63a5d19_0
  - pip=20.2.4=py37h06a4308_0
  - pot=0.7.0=py37h3340039_0
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - python=3.7.9=h7579374_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - readline=8.0=h7b6447c_0
  - scipy=1.5.3=py37h8911b10_0
  - setuptools=50.3.1=py37h06a4308_1
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.33.0=h62c20be_0
  - tk=8.6.10=hbc83047_0
  - tornado=6.1=py37h4abf009_0
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h6597ccf_2
  - pip:
    - absl-py==0.11.0
    - cachetools==4.1.1
    - chardet==3.0.4
    - click==7.1.2
    - dataclasses==0.6
    - faiss-cpu==1.6.4.post2
    - faiss-gpu==1.6.4.post2
    - fasttext==0.9.2
    - filelock==3.0.12
    - fsspec==0.8.4
    - future==0.18.2
    - google-auth==1.23.0
    - google-auth-oauthlib==0.4.2
    - grpcio==1.33.2
    - idna==2.10
    - importlib-metadata==2.0.0
    - joblib==0.17.0
    - markdown==3.3.3
    - oauthlib==3.1.0
    - packaging==20.4
    - protobuf==3.13.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybind11==2.6.1
    - pytorch-lightning==1.0.6
    - pyyaml==5.3.1
    - regex==2020.11.13
    - requests==2.25.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - sacremoses==0.0.43
    - sentencepiece==0.1.91
    - tensorboard==2.4.0
    - tensorboard-plugin-wit==1.7.0
    - tokenizers==0.9.3
    - torch==1.7.0
    - torchvision==0.8.1
    - tqdm==4.51.0
    - transformers==3.5.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.2
    - werkzeug==1.0.1
    - zipp==3.4.0

